# test elements xpath
locators = {
    'home_page_image': '//*[@id="header"]/div/div/div/div[1]/div/a/img',
    'sign_up_icon': '//*[@id="header"]/div/div/div/div[2]/div/ul/li[4]/a',
    'new_user_sign': '//*[@id="form"]/div/div/div[3]/div/h2',
    'sign_up_name': '//*[@id="form"]/div/div/div[3]/div/form/input[2]',
    'sign_up_email': '//*[@id="form"]/div/div/div[3]/div/form/input[3]',
    'sign_up_button': '//*[@id="form"]/div/div/div[3]/div/form/button',
    'acc_info_text': '//*[@id="form"]/div/div/div/div[1]/h2/b',
    'mr_radio': '//*[@id="id_gender1"]',
    'mrs_radio': '//*[@id="id_gender2"]',
    'name_field': '//*[@id="name"]',
    'password_field': '//*[@id="password"]',
    'day_list': '//*[@id="days"]',
    'month_list': '//*[@id="months"]',
    'year_list': '//*[@id="years"]',
    'news_checkbox': '//*[@id="newsletter"]',
    'offers_checkbox': '//*[@id="optin"]',
    'first_name_field': '//*[@id="first_name"]',
    'last_name_field': '//*[@id="last_name"]',
    'company_field': '//*[@id="company"]',
    'address_field': '//*[@id="address1"]',
    'address2_field': '//*[@id="address2"]',
    'country_list': '//*[@id="country"]',
    'state_field': '//*[@id="state"]',
    'city_field': '//*[@id="city"]',
    'zipcode_field': '//*[@id="zipcode"]',
    'mobile_number_field': '//*[@id="mobile_number"]',
    'create_button': '//*[@id="form"]/div/div/div/div[1]/form/button',
    'acc_created_text': '//*[@id="form"]/div/div/div/h2/b',
    'continue_after_create': '//*[@id="form"]/div/div/div/div/a',
    'logged_in_icon': '//*[@id="header"]/div/div/div/div[2]/div/ul/li[10]/a',
    'delete_icon': '//*[@id="header"]/div/div/div/div[2]/div/ul/li[5]/a',
    'acc_deleted_text': '//*[@id="form"]/div/div/div/h2/b',
    'continue_after_delete': '//*[@id="form"]/div/div/div/div/a',
}

# countries available in website
countries = ['India', 'United States', 'Canada', 'Australia', 'Israel', 'New Zealand', 'Singapore']
